title: ""
url: "http://anaveroneze.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "http://anaveroneze.github.io"
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "index"
 - name: "Updates"
   link: "updates"
 - name: "Research"
   link: "research"
 - name: "Experience"
   link: "experience"
 - name: "Founder"
   link: "founder"